import esbuild from "esbuild";
import { readFile } from "node:fs/promises";
import { builtinModules } from "node:module";
import process from "process";
import { patchMermaidWrapSwitch } from "./scripts/lib/mermaid-wrap-switch-patch.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const nodeBuiltins = [...builtinModules, ...builtinModules.map((moduleName) => `node:${moduleName}`)];

// Mirrors the manual patch Obsidian carries in their own bundled mermaid build:
// relax the edge-label wrap-switch from strict float equality to a rounded
// comparison so labels wrap instead of being clipped when the clamped
// measurement lands on a fraction. See scripts/lib/mermaid-wrap-switch-patch.mjs.
let wrapSwitchPatches = 0;

const mermaidWrapSwitchPatchPlugin = {
	name: "mermaid-wrap-switch-rounded-equality",
	setup(build) {
		build.onLoad({ filter: /mermaid[\\/]dist[\\/]chunks[\\/].+\.mjs$/ }, async (args) => {
			const contents = await readFile(args.path, "utf8");
			const { contents: patched, count } = patchMermaidWrapSwitch(contents);
			wrapSwitchPatches += count;
			if (count > 0) {
				process.stdout.write(`mermaid wrap-switch patch: ${count} replacement(s) in ${args.path.split(/[\\/]/).pop()}\n`);
			}
			return { contents: patched, loader: "js" };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...nodeBuiltins,
	],
	plugins: [mermaidWrapSwitchPatchPlugin],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await context.dispose();

	if (wrapSwitchPatches !== 1) {
		process.stderr.write(
			`error: expected exactly 1 mermaid wrap-switch patch site, found ${wrapSwitchPatches}.\n` +
				"The bundled mermaid version likely changed its minified shape; update\n" +
				"scripts/lib/mermaid-wrap-switch-patch.mjs (see the plan doc).\n",
		);
		process.exit(1);
	}

	const bundle = await readFile("main.js", "utf8");
	const marker = bundle.indexOf('"break-spaces"');
	const patchedInBundle = marker !== -1 && /Math\.round\(/.test(bundle.slice(Math.max(0, marker - 120), marker));
	if (!patchedInBundle) {
		process.stderr.write(
			'error: "break-spaces" wrap-switch in main.js is not preceded by the Math.round patch.\n',
		);
		process.exit(1);
	}
	process.stdout.write("mermaid wrap-switch patch verified in main.js\n");
	process.exit(0);
} else {
	await context.watch();
}
