---
config:
    xyChart:
        width: 700
        height: 420
---
xychart-beta
    title "Release activity"
    x-axis [Jan, Feb, Mar, Apr, May, Jun]
    y-axis "Merged PRs" 0 --> 20
    bar [4, 7, 9, 14, 18, 16]
    line [3, 5, 8, 11, 15, 19]
